name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      versionId:
        description: App version ID
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Run Simple Task
      run: |-
        echo "Hello, this is a simple workflow task!"
        echo  ${{ github.event.inputs.versionId }}
