name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      versionId:
        description: App version ID
        required: true
      otherInputs:
        description: all
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV_MAPS:  ${{ github.event.inputs.otherInputs }}
    steps:
    - name: Run Simple Task
      run: |-
         echo "Hello, this is a simple workflow task!"

         # Decode base64-encoded string
         DECODED_INPUTS=$(echo "$ENV_MAPS" | base64 --decode)

         # Print decoded inputs
         echo "Decoded inputs: $DECODED_INPUTS"

         # Extract and iterate over packs
         echo "Packs:"
         for item in $(echo "$DECODED_INPUTS" | jq -c '.packs[]'); do
            key=$(echo "$item" | jq -r '.key')
            value=$(echo "$item" | jq -r '.value')
            echo "Key: $key, Value: $value"
         done
        
