name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      versionId:
        description: App version ID
        required: true
      otherInputs:
        description: all
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV_MAPS:  ${{ github.event.inputs.otherInputs }}
    steps:
    - name: Run Simple Task
      run: |-
        echo "Hello, this is a simple workflow task!"
        echo  MY_MAP=${{ fromJSON(env.ENV_MAPS) }} >> $GITHUB_ENV
        echo  $ {{ env.ENV_MAPS }}
        echo  ${{ github.event.inputs.versionId }}
        echo  ${{ fromJSON(env.ENV_MAPS)[0] }}
        echo  ${{ fromJSON(env.ENV_MAPS)[0].key }}
        echo  ${{ fromJSON(env.ENV_MAPS)[0].value }}
        echo  ${{ fromJSON(env.ENV_MAPS)[0].length }}
        echo "Extracting key-value pairs:"
        IFS=',' read -ra KV_PAIRS <<< "${ENV_MAPS}"
        for pair in "${KV_PAIRS[@]}"; do
          IFS='=' read -r key value <<< "${pair}"
          echo "Key: ${key}, Value: ${value}"
        done
        
