name: Simple Workflow

on:
  workflow_dispatch:
    inputs:
      versionId:
        description: App version ID
        required: true
      otherInputs:
        description: all
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ENV_MAPS:  ${{ github.event.inputs.otherInputs }}
    steps:
    - name: Run Simple Task
      run: |-
        echo "Hello, this is a simple workflow task!"
        echo  ${{ fromJSON(env.ENV_MAPS) }}
        MY_MAP=${{ fromJSON(env.ENV_MAPS) }}
        echo $MY_MAP.other.janaka
        echo ${{ $MY_MAP.other.janaka }}
        echo ${{ fromJSON($MY_MAP).other.janaka}}
        echo  ${{ fromJSON(env.ENV_MAPS).other.janaka }}
        echo  ${{ github.event.inputs.versionId }}  
